version: '3.7'

services:  
  pg-db:
    image: postgres
    restart: always
    container_name: pg-db
    hostname: pg-db
    environment:
      POSTGRES_PASSWORD: P@ssw0rd # the username is postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/usr/databases

  jupyter:
    image: asami76/allspark:latest
    container_name: jupyter
    hostname: jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R
    user: root
    volumes:
      - .:/home/jovyan/work
    ports:
      - 8888:8888
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "mel.harc@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "P@ssw0rd"
    restart: always
    ports:
      - "5050:80"